import os
import warnings
import asyncio
import logging
import requests
import subprocess
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from crewai import Agent, Task, Crew
from langchain_openai import ChatOpenAI
from github import Github
from crewai_tools import BaseTool

# Logging Setup
logging.basicConfig(filename="agent_logs.txt", level=logging.INFO)
logging.info("Starting MACC application")

# Warnings Suppression & Event Loop Fix
os.environ["PYDANTIC_SKIP_VALIDATING_ASSIGNMENT"] = "1"
warnings.filterwarnings("ignore", category=DeprecationWarning)

try:
    loop = asyncio.get_event_loop()
except RuntimeError:
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

# Load environment variables
load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

if not OPENROUTER_API_KEY:
    raise ValueError("OPENROUTER_API_KEY not found in .env")
if not GITHUB_TOKEN:
    raise ValueError("GITHUB_TOKEN not found in .env")

# FastAPI setup
app = FastAPI(title="MACC - Multi-Agent AI Code Collaborator")

class ProjectRequest(BaseModel):
    spec: str
    github_repo: str

# Tools
class GitHubTool(BaseTool):
    name: str = "GitHubTool"
    description: str = "Push code to a GitHub repository"

    def _run(self, repo_name: str, code: str, filename: str) -> str:
        g = Github(GITHUB_TOKEN)
        user = g.get_user()
        try:
            repo = user.get_repo(repo_name.split("/")[-1])
        except:
            repo = user.create_repo(repo_name.split("/")[-1], auto_init=True)
        repo.create_file(filename, "Initial commit", code)
        return f"Pushed to https://github.com/{repo_name}/blob/main/{filename}"

    def push_to_repo(self, repo_name: str, code: str, filename: str) -> str:
        return self._run(repo_name, code, filename)

class WebSearchTool(BaseTool):
    name: str = "WebSearchTool"
    description: str = "Search the web for best practices or references"

    def _run(self, query: str) -> str:
        response = requests.get(f"https://api.duckduckgo.com/?q={query}&format=json")
        return response.json().get("Abstract", "No results found")

class CodeExecTool(BaseTool):
    name: str = "CodeExecTool"
    description: str = "Execute Python code and return output"

    def _run(self, code: str) -> str:
        with open("temp.py", "w") as f:
            f.write(code)
        result = subprocess.run(["python", "temp.py"], capture_output=True, text=True)
        return result.stdout or result.stderr

# Instantiate tools
github_tool = GitHubTool()
web_search_tool = WebSearchTool()
code_exec_tool = CodeExecTool()

# Language Model (OpenRouter + Grok)
try:
    llm = ChatOpenAI(
        model="x-ai/grok-4-fast:free",
        base_url="https://openrouter.ai/api/v1",
        api_key=OPENROUTER_API_KEY,
        default_headers={
            "HTTP-Referer": "http://localhost:8501",
            "X-Title": "MACC Project"
        }
    )
except Exception as e:
    raise ValueError(f"Failed to initialize LLM: {str(e)}")

# Agents
planner = Agent(
    role="Planner",
    goal="Break down project spec into tasks",
    backstory="Expert in project management and task decomposition.",
    llm=llm,
    tools=[web_search_tool]
)

coder = Agent(
    role="Coder",
    goal="Generate clean, functional code",
    backstory="Skilled programmer with expertise in Python and best practices.",
    llm=llm,
    tools=[code_exec_tool]
)

reviewer = Agent(
    role="Reviewer",
    goal="Ensure code quality and security",
    backstory="Code quality specialist with deep knowledge of linting and security.",
    llm=llm,
    tools=[code_exec_tool]
)

# Main MACC Workflow
def run_macc_agents(spec, github_repo):
    logging.info(f"Running agents for spec: {spec}, repo: {github_repo}")

    plan_task = Task(
        description=f"Break down this project spec into tasks: {spec}",
        agent=planner,
        expected_output="List of tasks in JSON format"
    )
    code_task = Task(
        description="Generate code for the given tasks",
        agent=coder,
        expected_output="Python code as a string"
    )
    review_task = Task(
        description="Review and improve the generated code",
        agent=reviewer,
        expected_output="Reviewed code and comments"
    )

    crew = Crew(agents=[planner, coder, reviewer], tasks=[plan_task, code_task, review_task])
    result = crew.kickoff()

    # Push to GitHub
    generated_code = result.get("code", "")
    if not generated_code:
        raise ValueError("No code was generated by the agents.")
    github_tool.push_to_repo(github_repo, generated_code, "main.py")

    return {
        "tasks": result.get("tasks"),
        "code": generated_code,
        "repo_url": f"https://github.com/{github_repo}"
    }

# FastAPI Endpoint
@app.post("/generate-project")
async def generate_project(request: ProjectRequest):
    try:
        result = run_macc_agents(request.spec, request.github_repo)
        logging.info(f"Generated project: {result}")
        return {"status": "success", "result": result}
    except Exception as e:
        logging.error(f"Error in generate_project: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

# Run the FastAPI Server
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)