# test_github_commit.py
import os
import pytest
from dotenv import load_dotenv
from main import github_tool, safe_slug, GitHubTool

load_dotenv()

# Test GitHub Token is available
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

@pytest.mark.skipif(not GITHUB_TOKEN, reason="GITHUB_TOKEN not set in .env")
def test_github_tool_can_push_code():
    """Test that GitHubTool can create/update a repository with code"""
    
    tool = GitHubTool()
    
    # Test data
    repo_name = f"test-macc-commit-{safe_slug('test ' + str(os.urandom(4).hex()))}"
    test_code = '''# Test file generated by MACC GitHub commit test
def main():
    print("Hello from MACC GitHub Commit Test!")
    print("This file was pushed successfully 🎉")

if __name__ == "__main__":
    main()
'''

    test_readme = f"""# {repo_name}

This is a test repository created by the MACC GitHub commit test.

- Generated at: {os.getenv('CURRENT_TIME', 'now')}
- Purpose: Testing GitHub integration

Generated by MACC (LangGraph version)
"""

    print(f"Testing push to repo: {repo_name}")

    try:
        # This will create the repo if it doesn't exist, or update it
        repo_url = tool.push(
            repo_name=repo_name,
            code=test_code,
            filename="main.py",
            readme=test_readme
        )

        assert repo_url is not None
        assert "github.com" in repo_url
        assert repo_name in repo_url

        print(f"✅ SUCCESS! Repository created/updated:")
        print(f"   {repo_url}")
        print(f"   File: main.py")
        print(f"   README.md also added")

        # Optional: Open in browser (macOS only)
        # import webbrowser
        # webbrowser.open(repo_url)

    except Exception as e:
        pytest.fail(f"GitHub push failed with error: {e}")


def test_github_tool_class_exists():
    """Basic sanity check"""
    tool = GitHubTool()
    assert hasattr(tool, 'push')
    assert callable(tool.push)


if __name__ == "__main__":
    # Run directly with: python test_github_commit.py
    print("=== Running GitHub Commit Test ===\n")
    test_github_tool_class_exists()
    test_github_tool_can_push_code()
    print("\n🎉 All GitHub commit tests passed!")